# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minhash_similarity_matrix <- function(sequences, k = 4L, num_hash = 50L) {
    .Call('_DynaAlign_minhash_similarity_matrix', PACKAGE = 'DynaAlign', sequences, k, num_hash)
}

calculateSimilarityMatrix <- function(sequences, matrixName = "BLOSUM62", gapOpen = 10L, gapExt = 4L) {
    .Call('_DynaAlign_calculateSimilarityMatrix', PACKAGE = 'DynaAlign', sequences, matrixName, gapOpen, gapExt)
}

