# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

similarityMH <- function(sequences, k = 4L, n_hash = 50L) {
    .Call('_DynaAlign_similarityMH', PACKAGE = 'DynaAlign', sequences, k, n_hash)
}

similarityNW <- function(sequences, matrixName = "BLOSUM62", gapOpen = 10L, gapExt = 4L) {
    .Call('_DynaAlign_similarityNW', PACKAGE = 'DynaAlign', sequences, matrixName, gapOpen, gapExt)
}

