# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name similarityMH
#' @title Compute MinHash Similarity Matrix
NULL

similarityMH <- function(sequences, k = 4L, n_hash = 50L) {
    .Call(`_DynaAlign_similarityMH`, sequences, k, n_hash)
}

#' @name similarityNW
#' @title Sequence Alignment using Needleman-Wunsch Algorithm
#' 
#' @description
#' This function performs global sequence alignment using the Needleman-Wunsch algorithm. 
#' It leverages substitution matrices (e.g., BLOSUM62, BLOSUM45, BLOSUM50, or BLOSUM80) 
#' to score alignments and handle amino acid sequences.
#' 
#' @param sequences A character vector of input sequences
#' @param matrixName A substitution matrix for scoring alignments. 
#'        Options include `"BLOSUM62"`, `"BLOSUM45"`, `"BLOSUM50"`, and `"BLOSUM80"`
#' @param gapOpen A numeric value specifying the penalty for opening a gap in the alignment
#' @param gapExt A numeric value specifying the penalty for extending an existing gap
#' @return A numeric matrix of pairwise similarities
#' @export
similarityNW <- function(sequences, matrixName = "BLOSUM62", gapOpen = 10L, gapExt = 4L) {
    .Call(`_DynaAlign_similarityNW`, sequences, matrixName, gapOpen, gapExt)
}

